cloudfoundry-incubator/kubo-deployment

docs/guides/accessing-kubernetes.md

I don't think the sshuttle example is correct. It should specify the bastion host as a remote server, not the local IP.

Fixes sshuttle command example

---

ci/kubo-deployment.yml

Changes that have already been applied to the main pipeline
- Stop using every version in the main pipeline
- Re-use the same version of kubo-deployment throughout

Main pipeline changes:

---

manifests/kubo.yml

[#145163059]
The release has two links to etcd: legacy manually implemented - `etcd` and community driven - `etcd_service`

Add links with same name as community release provides

---

bin/deploy_bosh
configurations/gcp/user-agent-config.yml

This cloud provider property will allow us to see how many people are using kubo on GCP.

Adding user agent string prefix for google bosh cpi deployment

---

docs/guides/gcp-cf/director.yml.erb
docs/guides/gcp/director.yml.erb

These did not get updated when we moved our blobstore/release bucket

Update kubo-release URL

---

configurations/vsphere/cloud-config.yml

* we are saving BOSH director to specific pool in vSphere, but not the
deployed VMs

Use resource pool in cloud config

---

bin/set_kubeconfig
configurations/generic/credhub.yml

From ci pipeline https://ci.kubo.sh/teams/main/pipelines/kubo-deployment/jobs/deploy-workload-gcp/builds/24
```
+ credhub login -u credhub-user -p unzqvrjr709qu0erfrmd -s https://10.0.252.252:8844 --skip-tls-validation
Warning: The targeted TLS certificate has not been verified for this connection.
Warning: The --skip-tls-validation flag is deprecated. Please use --ca-cert instead.
Setting the target url: https://10.0.252.252:8844
Login Successful
```
[#145644667]

Fix Credhub warning for skip_ssl_verification

---

configurations/generic/project-config.yml

`set_kubeconfig` require `kubernetes_master_port` property which is missing in generic configuration templates. https://github.com/cloudfoundry-incubator/kubo-deployment/blob/0c4f1b6d7f4f8f2bd7dfd42ca0b8a7cf4631b9c8/bin/set_kubeconfig#L59
https://github.com/cloudfoundry-incubator/kubo-deployment/commit/5538764c17de2985ca6a694d4a9e212852bac894 commit added this property only to test files.
```
++ bosh-cli int /kubo/director.yml --path /kubernetes_master_port
Expected to find a map key 'kubernetes_master_port' for path '/kubernetes_master_port' (found map keys: 'auth_url', 'az', 'credhub_encryption_key', 'credhub_release_url', 'default_key_name', 'default_security_groups', 'deployments_network', 'director_name', 'dns_recursor_ip', 'external-kubo-port', 'iaas', 'internal_cidr', …
```

Add kubernetes_master_port property to generic config

---

docs/user-guide/README.md
docs/user-guide/platforms/aws/install-bosh.md
docs/user-guide/platforms/aws/kubo-infrastructre.tf
docs/user-guide/platforms/aws/paving.md
docs/user-guide/platforms/aws/prerequisites.md
docs/user-guide/platforms/aws/setup_helpers
docs/user-guide/routing/aws/kubo-lbs.tf
docs/user-guide/routing/aws/load-balancing.md
docs/user-guide/routing/exposing-apps.md

Included in this PR:
- Prerequisites doc
- Paving guide and Terraform script, including bastion setup in Terraform
- Helper scripts for setting up the env config
- Install BOSH guide
- iaas routing guide and Terraform script, which deploys a Load Balancer for Kubernetes worker nodes
- Links to above docs in main README
- Additional section in accessing cluster guide
Not included: 
- AWS cloud config settings for services of type LoadBalancer
- AWS cloud config settings for persistent volumes
- Actual health checks for the nodes. Currently, the health checks just check if the nodes are up and running, not if the nodes are actually running Kubernetes.
To test this, I manually ran through the instructions to deploy a cluster with iaas routing, ran nginx on the cluster and accessed the nginx …

Install Kubo Guide on AWS

---

bin/lib/deploy_utils
configurations/gcp/project-config.yml
docs/user-guide/platforms/gcp/kubo-infrastructre.tf
docs/user-guide/routing/exposing-apps.md
docs/user-guide/routing/gcp/kubo-lbs.tf
docs/user-guide/routing/gcp/load-balancing.md
manifests/ops-files/gcp-cloud-provider.yml
manifests/ops-files/load_balancer_target_pools.yml
src/kubo-deployment-tests/generate_cloud_config_test.go

Included:
- Adds the worker-node-tag field to the cloud-provider job so that the cloud-provider job can put the tag in the k8s cloud-config
- Removes the worker load balancer, which is no longer necessary
- Adds the securityAdmin role to the kubernetes node's service account, which is necessary to create firewall rules
- Tests are [here](https://github.com/pivotal-cf-experimental/kubo-ci/pull/7), these PRs will need to be merged at the same time
- Pipeline is [here](https://ci.kubo.sh/teams/main/pipelines/kubo-deployment-current-branch-mkjelland-2). Currently there is 1 failing test in vsphere, but this test is failing in other branches too and is unrelated to these changes.

Add k8s cloud config value for LoadBalancer support

---

configurations/vsphere/cloud-config.yml

Adding more vCPUs to the Workers for vSphere deployments. Aligning it with other IaaS worker specs (e.g: [OpenStack](https://github.com/jaimegag/kubo-deployment/blob/master/configurations/openstack/cloud-config.yml#L19) m1.large = 4 vCPU - 8GB RAM)
[AWS](https://github.com/jaimegag/kubo-deployment/blob/master/configurations/aws/cloud-config.yml#L23) (m4.xlarge) has also 4 vCPUs though more RAM (16 GB)
[GCP](https://github.com/jaimegag/kubo-deployment/blob/master/configurations/gcp/cloud-config.yml#L40) (n1-standard-2) has 2 vCPU. This could be bumped also but since it has a direct $$ impact I didn't change it.

Bumping CPUs for workers in vSphere

---

docs/user-guide/platforms/gcp/prerequisites.md

Following the [Paving the Infrastructure for Kubo on GCP](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/master/docs/user-guide/platforms/gcp/paving.md) instructions I ran into this error:
```
Error applying plan:
1 error(s) occurred:
* google_service_account.kubo: 1 error(s) occurred:
* google_project_iam_policy.policy: Error retrieving IAM policy for project "[REDACTED]": googleapi: 
Error 403: Google Cloud Resource Manager API has not been used in project [REDACTED] before
or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=[REDACTED] 
then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our 
systems and retry., accessNotConfigured
```
This …

Add Cloud Resource Manager API enabled as a GCP prerequisite

---

docs/user-guide/platforms/gcp/paving.md

The [Paving the Infrastructure for Kubo on GCP](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/master/docs/user-guide/platforms/gcp/paving.md) instructions suggests creating a new subnet, but the subnet is [created by terraform](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/master/docs/user-guide/platforms/gcp/kubo-infrastructre.tf#L108).
Worth noting that if https://github.com/cloudfoundry-incubator/kubo-deployment/pull/146 is merged then the doc should be updated again.

Fix GCP paving instructions: GCP subnet is created by terraform

---

configurations/openstack/project-config.yml

Must specify project name, not project ID.

Fix comment

---

manifests/kubo.yml

[#150849676]
Signed-off-by: Brendan Nolan <bnolan@pivotal.io>

Upgrade haproxy to 8.4.0 public release

---

manifests/kubo.yml

Use static name with internal domain for kubelet certificate

---

bin/lib/deploy_utils
manifests/kubo.yml

* Add the ability to have additional manifest files applied - This will
allow CI to change to compiled versions
PKS needs this as we use the kubo.yml from the tile and we don't to be
fixed to compiled versions
[#152678378]
Signed-off-by: Brendan Nolan <bnolan@pivotal.io>

Fix the default kubo.yml to not compiled versions

---

manifests/kubo.yml

I chose a random name that is not a real name for the worker VM.
But it is definitely not `kubernetes_master_host`.

Change common_name for docker cert

---

bin/set_kubeconfig

Without a namespace based on the bosh environment, clusters given the
same name will collide with one another and users must re-run
set_kubeconfig every time they wish to switch between a cluster. With
the namespaces, that should reduce the likelihood of a collision and
allow users to switch using `kubectl config use-context <context-name>`.
Issue #223.
[#152752429]

Added namespaces to the cluster, creds and context in set_kubeconfig

---

manifests/ops-files/allow-privileged-containers.yml

This PR in in addition to https://github.com/cloudfoundry-incubator/kubo-release/pull/153

Toggle allow privileged for kubelet.

---

docs/terraform/gcp/platform/kubo-infrastructure.tf

The “BOSH1” CLI was a rubygem, bosh_cli. “BOSH2” is a standalone Go binary.
When installed together, BOSH1’s path takes precedence over BOSH2. This
breaks deploy_bosh and deploy_k8s, which rely on BOSH2 features.
[#154432300]

Remove legacy BOSH CLI

---

docs/terraform/gcp/platform/kubo-infrastructure.tf

* This is required in order to pull images from your project's container
registry
Signed-off-by: Brenda Chan <brchan@pivotal.io>

Adds 'storage.objectViewer' role for master and worker service accounts

---

bosh-deployment/runtime-configs/dns.yml
manifests/ops-files/use-runtime-config-bosh-dns.yml

If the end user uses runtime config with latest bosh dns.
Apply following runtime config to the bosh director
https://github.com/cloudfoundry/bosh-deployment/blob/master/runtime-configs/dns.yml
Deploy CFCR with manifests/ops-files/use-runtime-config-bosh-dns.yml
```release-note
CFCR can be deployed with latest Bosh DNS runtime config
```

Remove DNS API variables if runtime config is used

---

manifests/cfcr.yml

I think it has been used for glusterfs experiment long time ago.

Persistent disk is not used for kubelet

---

bin/test-standard-ops.sh
manifests/README.md
manifests/ops-files/add-syslog-tls.yml
manifests/ops-files/add-syslog.yml
manifests/ops-files/example-vars-files/add-syslog-tls.yml
manifests/ops-files/example-vars-files/add-syslog.yml

This PR adds ops-file to enable syslog forwarding with [syslog-release](https://github.com/cloudfoundry/syslog-release).
Configure a syslog endpoint in `add-syslog.yml` and `add-syslog-tls.yml` (if TLS is required) and check whether component logs (such as kube-apiserver) are received in the syslog server.
No
No
No
Forwarding component logs to a syslog endpoint
```release-note
Added ops-files to forward component logs to a syslog endpoint.
```

Add syslog forwarder

---

bin/test-standard-ops.sh
manifests/README.md
manifests/ops-files/change-etcd-metrics-url.yml

This PR add an ops file to change etcd's metrics url so that operator can use a separate port and protocol for the metrics endpoint.
run `./bin/run_tests`
no
no
no
related to https://github.com/cloudfoundry-incubator/cfcr-etcd-release/pull/9
```release-note
Added ops-files to change the protocol and port of the metrics endpoint of etcd.
```

Add ops-file to change etcd's metrics url

---

manifests/cfcr.yml

https://bosh.io/docs/runtime-config/#placement-rules
Signed-off-by: Leah Hanson <lhanson@pivotal.io>
The addons block was adding those addons to every stemcell type, not only xenial/trusty ones.
Spin up a Windows node, see that it tries to place addon jobs onto that VM.
Nope
Nope
Nope
None filed
```release-note
Fixed addons block in cfcr.yml to properly exclude non-Xenial/Trusty stemcells from addon jobs.
```

Fix addons block

---

manifests/ops-files/iaas/azure/cloud-provider.yml
manifests/ops-files/iaas/gcp/add-service-key-master.yml
manifests/ops-files/iaas/gcp/add-service-key-worker.yml
manifests/ops-files/iaas/gcp/add-subnetwork-for-internal-load-balancer.yml
manifests/ops-files/iaas/gcp/cloud-provider.yml
manifests/ops-files/iaas/openstack/cloud-provider.yml
manifests/ops-files/iaas/vsphere/cloud-provider.yml
manifests/ops-files/iaas/vsphere/set-working-dir-no-rp.yml

This PR supports the configurable cloud-config exposed in https://github.com/cloudfoundry-incubator/kubo-release/pull/263 by updating the various ops-files.
Deploy with a cloud-provider and observe that the manifest renders into the expected INI file. Follow up by using a cloud-provider specific bit of functionality like a Load Balancer or Persistent Volume.
[Yes](https://github.com/cloudfoundry-incubator/kubo-release/pull/263).
No.
Not generally, unless operators are using custom ops-files to enable other cloud-provider options not covered by the default ops-files.
Those …

Support configurable cloud-config

---

manifests/cfcr.yml
manifests/ops-files/set-certificate-duration.yml

This PR bumps the kubernetes binaries to v1.12.2. Additionally, it includes changes to generate a serving certificate for kube-controller-manager. v1.12.2 now requires either to have a self-signed certificate created to a specified `--cert-dir` or supply the proper certificate and private key via `--tls-cert-file` and `--tls-private-key-file`.
Deploy a CFCR cluster with these changes. Run integration, conformance, and upgrade against it. 
Yes: https://github.com/cloudfoundry-incubator/kubo-release/pull/271
Nope. 
Yes, because its an update of the k8s binaries. 
**Which …

Bump to k8s 1.12.2

---

manifests/ops-files/enable-csi-shared-mounts.yml

This PR adds an ops-file to allow operators to configure `docker` to enable shared mounts.
When the ops-file is applied, the `docker` job on the `worker` should be configured with `shared_mounts_enable` set to true.
No.
No.
No.
This is required to configure CSI support in Kubernetes. See this [doc](https://kubernetes-csi.github.io/docs/Setup.html#enabling-mount-propagation) for details.
```release-note
Added an ops-file to enable shared mounts for CSI support. See the [Kubernetes CSI Setup …
```

Add ops-file to enable CSI shared mounts

---

manifests/cfcr.yml

This PR puts a default audit policy configuration into the manifest in order to support https://github.com/cloudfoundry-incubator/kubo-release/pull/283.
Deploy the cluster using this PR and https://github.com/cloudfoundry-incubator/kubo-release/pull/283. Make a small change to the `audit-policy` property, and compare the contents of the manifest and the contents of the file at `/var/vcap/jobs/kube-apiserver/config/audit_policy.yml`.
https://github.com/cloudfoundry-incubator/kubo-release/pull/283
No.
No.
```release-note
* …
```

Added default audit policy configuration to the manifest

---

manifests/cfcr.yml

This works around issue #370, which should ideally be fixed by upstream
Kubernetes. By preempting logrotate, we let kube-apiserver's log
rotation facility handle all rotation. In order to keep in line with
logrotate's behavior, we can also set the maximum number of backups to
7.
Observe audit log rotation and check the backups for corruption.
No.
No.
No.
#370 
```release-note
* `kube-apiserver` now handles all log rotations for `audit.log` - this should prevent the data corruption seen when `logrotate` would handle the …
```

Updated kube-apiserver's audit log flags to preempt logrotate

---

bin/test-standard-ops.sh
manifests/README.md
manifests/ops-files/iaas/vsphere/windows/cloud-provider.yml
manifests/ops-files/iaas/vsphere/windows/use-vm-extensions.yml
manifests/ops-files/misc/deployment-name.yml
manifests/ops-files/misc/version.yml
manifests/ops-files/use-hostgw.yml
manifests/ops-files/windows/add-worker.yml
manifests/ops-files/windows/enable-rdp.yml
manifests/ops-files/windows/scale-to-one-az.yml
manifests/ops-files/windows/use-hostgw.yml
manifests/ops-files/windows/vm-types.yml

This adds the opsfiles for deploying a cluster with a windows worker.
- Windows workers will only support hostgw network backend for now.
- Add ops-file to make linux nodes also use hostgw backend (should be
applied to any cluster with windows workers).
- Add scale-to-one-az opsfile for windows worker (does the same thing as
the standard scale-to-one-az opsfile).
Run test added in kubo-ci PR.
Yes
Yes
No, as long as you don't add windows nodes to your clusters.
Lack of windows support.
```release-note
Add ops-files for …
```

Add opsfiles for adding a Windows worker

---

manifests/cfcr.yml

...so that it is possible to avoid eviction thresholds when log files grow
**What this  does / why we need it**:
Fixes the bug described here:
https://www.pivotaltracker.com/story/show/164157527
**How can this  be verified?**
Deploy CFCR. Create and run a pod that writes data to an emptyDir type volume (sample code can be found [here](https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-volumes-example-nfs-persistent-volume.html), and observe that it writes data into the `/var/vcap/data/kubelet` mount point. The specific path on each worker VM will be something like: `/var/vcap/data/kubelet/pods/xxxxxxx-xxxx-xxxxxxxx/volumes/kubernetes.io~empty-dir/simple-vol/file.txt`
No
No (but should there …

Set the root-dir to a partition that is scalable

---

bin/test-standard-ops.sh
manifests/README.md
manifests/ops-files/example-vars-files/fs-inotify-limit.yml
manifests/ops-files/set-fs-inotify-limit.yml

Signed-off-by: Brady Love <blove@pivotal.io>
We used this opsfile to up the fs.inotify limit such that fluent-bit's tail plugin does not overwhelm the fs inotify limit. This was added to the master for future work. 
cat /proc/sys/fs/inotify/max_user_watches shows 65k watches
/etc/sysctl.d/71-bosh-os-conf-sysctl.conf shows this line as well. 
No
We didn't add any changes, but can if needed for testing etc.
No
https://www.pivotaltracker.com/story/show/164228988
```release-note
Added a opsfile to up fs.inotify limit for log …
```

Add opsfile to up fs.inotify limit to allow more file watchers

---

manifests/ops-files/enable-bbr.yml

As part of a [PR into cfcr-etcd](https://github.com/alamages/kubo-deployment/tree/bbr-backup-one-restore-all) we introduced a new manifest property for the etcd bbr job. This PR is to add it to the ops file that enables the job. This property enables BBR to backup and restore multi-master clusters when using version [v1.5.0 and later](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/tag/v1.5.0).
Thanks,
Jake & @MModhaPivotal

Template bbr.backup_one_restore_all property for bbr-etcd job

---

manifests/ops-files/windows/add-worker.yml

1. **Updates windows workers to run on 2019.** This updates the expected OS version of the stemcell and the value of the taint for the windows nodes. In order for this PR to pass in your CI pipeline, you'll need to adjust the job that uploads the windows stemcell to the Bosh director, to upload a 2019 stemcell.
2. **Sets `runtime-request-timeout` on windows.** Setting this property causes some kubelet requests that don't normally have a timeout to have a timeout set. The goal is to work around some instability caused by [hangs like this one](https://github.com/kubernetes/kubernetes/issues/75299).
On a bosh director where the only windows stemcell is 2019, deploy the cluster as usual in host-gw mode and see that it …

Update Windows workers to use 2019 stemcells

---

manifests/ops-files/windows/add-worker.yml

Windows support now exists in a separate release and so it needs to be consumed.
Deploy a Windows worker using the ops-file.
No.
CI also needs to be updated to consume the external release - pending.
No.
None.

Update windows/add-worker.yml to fetch external windows release

---

manifests/ops-files/set-certificate-duration.yml

Forget to add new cert to update duration opsfile
No
No
No
```release-note
```

Add tls-etcdctl-root to set-certificate-duration.yml

---

manifests/ops-files/windows/use-overlay.yml

Allows Windows deployments to override the vni/port used for the cluster
Same as https://github.com/cloudfoundry-incubator/kubo-release/pull/320
Yes
No
No
```release-note
Adds an opsfile to support setting vxlan VNI and port to values supported by Windows
```

Add opsfile for setting windows overlay vni/port

---

manifests/cfcr.yml

I would like to have better `ulimit` by default.
https://github.com/cloudfoundry-incubator/kubo-ci/blob/master/src/tests/integration-tests/generic/ulimit_test.go#L25
Nope
Maybe change test to have bigger default, but not required
NA
I can't start Eirini on default CFCR cluster.
```release-note
Bump ulimit to 1048576
```

Bump ulimit to be the same as in GKE

---

Gemfile.lock

Signed-off-by: Larry Hamel <lhamel@pivotal.io>
The docker image was updated to use bundler 2.0.2. This change aligns our lockfile with that new version.
n/a (pipeline runs)
yes, but only to fix the same gemfile issue
no
no
broken pipeline
```release-note
N/A
```

Update ruby Gemfile.lock to use bundler 2.0.2

---

manifests/cfcr.yml
manifests/ops-files/non-precompiled-releases.yml
manifests/ops-files/windows/add-worker.yml

This PR allows us to use the docker-boshrelease that has the docker-windows job. It forces the user to use the uncompiled docker-boshrelease when a user adds windows workers. This change does the same thing for the recombined kubo/kubo-windows release. 
Run it through the normal pipelines
Yes. There is a change to bring the Windows jobs back into that release.
Yes. Some scripts need to be updated to support compiling the windows releases
No
```release-note
This release recombines the kubo-release and kubo-release-windows. It …
```

Combine windows

---

manifests/ops-files/windows/add-worker.yml
manifests/ops-files/windows/pause-image.yml

This is the recommended pause image for Windows, and has [wincat](https://github.com/kubernetes-sigs/sig-windows-tools/tree/master/cmd/wincat) in it that will enable port-forwarding starting in k8s 1.15
https://github.com/kubernetes/kubernetes/pull/75479
Deploy it with a 1.15 Windows node, see that you can use `kubectl port-forward` now.
No
No
No
```release-note
Port forwarding is now supported for Windows containers
```

Switch to Microsoft's pause image

---

manifests/cfcr.yml
manifests/ops-files/windows/add-worker.yml
manifests/ops-files/windows/change-cidrs.yml

Pull the pod CIDR from flanneld on Linux, expose the kubedns service IP with an opsfile. Not sure whether the Windows jobs will continue to come from kubo-release-windows or kubo-release now but ignoring that problem for now :).
https://github.com/cloudfoundry-incubator/kubo-release-windows/pull/18
https://github.com/cloudfoundry-incubator/kubo-release/pull/349

Allow customizing Windows CIDRs

---

manifests/cfcr.yml

Authored-by: Gene Hynson <ghynson@pivotal.io>
Authored-by: Gavin Morgan <gmorgan@pivotal.io>
This PR introduces the empty key for `k8s-args` for the `kube-scheduler` job to prevent unwanted null pointers at `create cluster` time.
The PR doesn't affect functionality. It just makes the manifest more consistent. Every kube job should have `k8s-args` key.
See that a bosh deployment with this manifest is successful and that kube-scheduler has an empty map for k8s-args.
no
no
no
It fixes a potential null pointer exception if consuming projects …

Adds empty tag k8s-args to kube-scheduler
