cloudfoundry-incubator/kubo-deployment

ci/kubo-deployment.yml
=> Always trigger tarball uploads for the latest version

README.md
=> Add CI badges for the relevant jobs

ci/kubo-deployment-current-branch.yml, ci/kubo-deployment-pr.yml, ci/kubo-deployment.yml, ci/kubo-release-pr.yml, ci/scripts/pod-to-pod.sh, ci/specs/guestbook.yml, ci/tasks/pod-to-pod.yml
[#141118027] - added tests based on https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml
=> Added pod-2-pod communication tests to the pipeline.

bin/set_kubeconfig, src/kubo-deployment-tests/generate_cloud_config_test.go, src/kubo-deployment-tests/kubo_deployment_tests_suite_test.go, src/kubo-deployment-tests/set_kubeconfig_test.go
+ Fixed shellcheck warning
[#141626951]
=> Added tests for set kubeconfig

ci/kubo-deployment-pr.yml
The changes in this PR are already applied.
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>
=> kubo-deployment PR pipeline cleanup

ci/environments/gcp-arsenal/director.yml, ci/environments/gcp-baldwin/director.yml, ci/environments/gcp-cyclone/director.yml, ci/environments/gcp-drum/director.yml, ci/environments/gcp-east/director.yml, ci/environments/gcp/director.yml, ci/kubo-deployment-current-branch.yml, ci/kubo-deployment-pr.yml, ci/kubo-deployment.yml, ci/kubo-release-pr.yml, ci/scripts/deploy-k8s-instance.sh, ci/scripts/deploy-k8s-workload.sh, ci/set_pipeline, ci/specs/nginx.yml, ci/tasks/deploy-k8s-instance.yml, configurations/generic/project-config.yml, configurations/generic/project-secrets.yml, docs/guides/accessing-kubernetes.md, docs/guides/gcp-oss-cf/README.md, docs/guides/gcp-oss-cf/director-secrets.yml.erb, docs/guides/gcp-oss-cf/director.yml.erb, docs/guides/gcp-pcf/README.md, docs/guides/gcp-pcf/director.yml.erb, manifests/kubo.yml
This is ready for review, but cannot be merged until the corresponding [PR](https://github.com/pivotal-cf-experimental/kubo-release/pull/24) in kubo-release is merged.
=> Configuration, docs and integration tests for route sync

bin/generate_kubo_manifest, bin/lib/deploy_utils, src/kubo-deployment-tests/generate_manifest_test.go
generate_kubo_manifest command didn't work with relative path.
=> Fix generate manifest

ci/environments/gcp-arsenal/director.yml, ci/environments/gcp-baldwin/director.yml, ci/environments/gcp-cyclone/director.yml, ci/environments/gcp-drum/director.yml, ci/environments/gcp-east/director.yml, ci/environments/gcp/director.yml
=> Remove unused properties

README.md
=> Adding badge for build-kubo-release ci job

bin/destroy_bosh
Support destruction of KuBOSH on OpenStack
[#140681955]
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>
=> Added OpenStack to the `destroy_bosh` script

bin/lib/deploy_utils, configurations/generic/project-config.yml, docs/guides/gcp-oss-cf/director.yml.erb, docs/guides/gcp-pcf/director.yml.erb, manifests/kubo.yml, manifests/ops-files/add-http-proxy.yml, manifests/ops-files/add-https-proxy.yml, manifests/ops-files/add-no-proxy.yml, src/kubo-deployment-tests/generate_manifest_test.go, src/kubo-deployment-tests/resources/environments/with_http_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_http_proxy/name-vars.yml, src/kubo-deployment-tests/resources/environments/with_https_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_https_proxy/name-vars.yml, src/kubo-deployment-tests/resources/environments/with_no_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_no_proxy/name-vars.yml
=> Added docker env/proxy capability to manifest generation.

configurations/generic/project-config.yml, manifests/kubo.yml
[#143113113]
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>
=> Add NATS properties: port, username

manifests/kubo.yml, manifests/ops-files/add-http-proxy.yml, manifests/ops-files/add-https-proxy.yml, manifests/ops-files/add-no-proxy.yml, src/kubo-deployment-tests/generate_manifest_test.go
Variable was being applied at the wrong level in our manifest.
[#139670355]
=> Fix docker proxy settings issue

docs/guides/gcp-oss-cf/director.yml.erb, docs/guides/gcp-pcf/director.yml.erb
Some changes were made to the director.yml file, we added a field for iaas and made routing-cf-nats-internal-ip an array. This PR will make the same change in the example director files.
=> Fixing director yml example files

bin/lib/deploy_utils, manifests/kubo.yml, manifests/ops-files/cf-routing.yml
This will help us with adding other type of routing (i.e. Google Load Balancer)
[#145157789]
Signed-off-by: Alex Slynko <oslynko@pivotal.io>
=> Extract cf specific fields in manifest into ops file

manifests/kubo.yml
=> Use community etcd bosh release

bin/deploy_bosh, bin/destroy_bosh, configurations/vsphere/cloud-config.yml, configurations/vsphere/project-config.yml, src/kubo-deployment-tests/deploy_bosh_test.go, src/kubo-deployment-tests/destroy_bosh_test.go, src/kubo-deployment-tests/resources/environments/test_vsphere/director.yml
Adds support to deploy/destroy a director to vsphere
[#135571805]
=> Add vsphere to our deploy scenarios

manifests/kubo.yml
See [kubo-release#43](https://github.com/pivotal-cf-experimental/kubo-release/issues/43) for more detail
=> Update to etcd v3

docs/guides/customized-installation.md
=> Add proxy documentation

docs/guides/gcp/README.md, docs/guides/gcp/kubo.tf
- Adds a Kubo CIDR as a var
- Documentation fixes
- Fix for a bug preventing kubo deployment to a non-default region.
=> Fixes for Terraform and documentation

bin/deploy_bosh, bin/deploy_k8s, bin/lib/deploy_utils, bin/set_kubeconfig, configurations/generic/credhub.yml, configurations/generic/project-config.yml, docs/guides/customized-installation.md, docs/guides/gcp-cf/director.yml.erb, docs/guides/gcp/director.yml.erb, manifests/kubo.yml, manifests/ops-files/cf-routing.yml, manifests/ops-files/remove-variables.yml, src/kubo-deployment-tests/deploy_bosh_test.go, src/kubo-deployment-tests/generate_manifest_test.go, src/kubo-deployment-tests/resources/environments/secretless/director.yml, src/kubo-deployment-tests/resources/environments/test_gcp/director.yml, src/kubo-deployment-tests/resources/environments/test_openstack/director.yml, src/kubo-deployment-tests/resources/environments/test_vsphere/director.yml, src/kubo-deployment-tests/resources/environments/test_vsphere_with_creds/director.yml, src/kubo-deployment-tests/resources/environments/with_http_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_https_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_no_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_ops/director.yml, src/kubo-deployment-tests/resources/environments/with_vars/director.yml, src/kubo-deployment-tests/set_bosh_environment_test.go, src/kubo-deployment-tests/set_kubeconfig_test.go
Upgrading to Credhub 1.0.0
https://github.com/pivotal-cf-experimental/kubo-deployment/issues/99
[#145644667]
=> Upgrading to Credhub 1.0.0

docs/guides/customized-installation.md, docs/guides/gcp-cf/kubo.tf, docs/guides/gcp/README.md
Reapplying the docs correction from here #93
=> Update credhub cli ref in docs

bin/set_kubeconfig, configurations/generic/project-config.yml, docs/guides/gcp/README.md, docs/guides/gcp/director.yml.erb, manifests/kubo.yml, src/kubo-deployment-tests/resources/environments/test_gcp/director.yml, src/kubo-deployment-tests/resources/environments/test_gcp_with_creds/director.yml, src/kubo-deployment-tests/resources/environments/test_openstack/director.yml, src/kubo-deployment-tests/resources/environments/with_http_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_https_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_no_proxy/director.yml, src/kubo-deployment-tests/resources/environments/with_ops/director.yml, src/kubo-deployment-tests/resources/environments/with_vars/director.yml
AWS provides hostname for ELB
[#146712889]
Signed-off-by: Akshay Mankar <amankar@pivotal.io>
=> Use kubernetes_api_host instead of ip

manifests/kubo.yml
Fixes https://github.com/cloudfoundry-incubator/kubo-release/issues/69 & https://github.com/cloudfoundry-incubator/kubo-release/issues/53
[#145942903]
=> Use Kubo-etcd release

manifests/kubo.yml, manifests/ops-files/cf-routing.yml
This allows using connecting to Kubernetes api from the pod
[#148340689]
=> Add internal Kubernetes service ip address to certificate

docs/user-guide/README.md, docs/user-guide/platforms/openstack/install-bosh.md, docs/user-guide/platforms/vsphere/install-bosh.md, docs/user-guide/routing/cf-apps.md, docs/user-guide/routing/cf.md, docs/user-guide/routing/openstack/haproxy-routing.md
Doc change suggestions to improve the flow for vsphere and openstack.
Also some additional details to help prevent some common mistakes.
=> Docs review

bin/lib/deploy_utils, configurations/generic/project-config.yml
Signed-off-by: Bengt Hammarlund <bgadelhahammarlund@pivotal.io>
=> Add file checks for ops-files when generating a manifest

manifests/ops-files/cf-routing.yml
* Removed nginx job
* Removed flanneld job
* Removed kubernetes-proxy job
[#148898685]
=> Renamed proxy instance to route-sync

configurations/aws/cloud-config.yml, configurations/aws/project-config.yml, docs/user-guide/README.md, docs/user-guide/platforms/aws/.gitignore, docs/user-guide/platforms/aws/install-bosh.md, docs/user-guide/platforms/aws/kubo-infrastructre.tf, docs/user-guide/platforms/aws/setup_helpers, manifests/ops-files/aws-cloud-provider.yml
Fixes [kubo-release#88](https://github.com/cloudfoundry-incubator/kubo-release/issues/88)
=> Support for persistent volumes on AWS

docs/user-guide/README.md, docs/user-guide/platforms/aws/install-bosh.md, docs/user-guide/platforms/aws/prerequisites.md, docs/user-guide/routing/aws/load-balancing.md, docs/user-guide/routing/gcp/load-balancing.md
=> Addressing doc issues for AWS installation guides

docs/user-guide/platforms/aws/install-bosh.md, docs/user-guide/platforms/aws/kubo-infrastructure.tf
=> Make ssh into bastion step in guide easier to follow

docs/user-guide/platforms/gcp/kubo-infrastructure.tf
It was 1 year old!
BTW why not Ubuntu 16.04?
=> Update GCP image 

manifests/cfcr.yml
=> Bump Bosh DNS

manifests/README.md
=> Deploy using bosh-lite

manifests/README.md
=> Fixing typo in variable

manifests/cfcr.yml, manifests/ops-files/change-cidrs.yml, manifests/ops-files/set-certificate-duration.yml
[#163786805]
pipeline
yes
yes
no
https://www.pivotaltracker.com/story/show/163786805
```release-note
```
=> Add users field and more cfcr certs to cfcr etcd job

manifests/ops-files/windows/add-worker.yml
Sync with changes from https://github.com/cloudfoundry-incubator/kubo-release/pull/321 @tvs
=> Add flannel etcd certs
